-- SUPERSEDED — do not apply.
--
-- This migration created dropship_listings in the `public` schema, which is
-- wrong for this app: Supabase clients are scoped to the user's tenant schema
-- via `db: { schema }` (src/lib/supabase/server.ts), so queries looked for
-- tenant_<x>.dropship_listings and failed.
--
-- Replaced by supabase/migrations/019_dropship_supplier_price.sql, which
-- creates the table in every tenant schema (run_on_all_tenant_schemas),
-- migrates any rows out of public.dropship_listings, and drops the public
-- table. New tenants get the table via provision_tenant_schema() in
-- supabase/migrations/005_tenant_provisioning.sql.
